server:
  port: 9004

spring:
  application:
    name: auth-service
  datasource:
    username: 'myportfolio'
    url: jdbc:mysql://mysql:3306/auth
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://myzipkin:9411
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://my-eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE