server:
  port: 9004

spring:
  application:
    name: auth-service
  datasource:
    username: 'myportfolio'
    url: jdbc:mysql://mysql:33061/auth
    password: 'password'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
  zipkin:
    base-url: http://myzipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://my-eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE