server:
  port: 9004

spring:
  application:
    name: auth-service
  zipkin:
    base-url: http://myzipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://my-eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true