services:

  mysql:
    container_name: mysql
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_USER: 'myportfolio'
      MYSQL_PASS: 'password'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - mysql

  zipkin:
    image: openzipkin/zipkin
    container_name: myzipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  eureka-server:
    image: rob097/eureka-server:latest
    container_name: my-eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin

########################################################################################################################

  apigw:
    image: rob097/apigw:latest
    container_name: myapigw
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server

  auth-service:
    image: rob097/auth-service:latest
    container_name: auth-service
    ports:
      - "9004:9004"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server

  core:
    image: rob097/core:latest
    container_name: core
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - mysql
    depends_on:
      - zipkin
      - mysql
      - eureka-server

networks:
  mysql:
    driver: bridge
  spring:
    driver: bridge

volumes:
  mysql:
  pgadmin: