server:
  ssl:
    enabled: true
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8443

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://myzipkin:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - POST
              - GET
              - OPTIONS
              - PUT
              - DELETE
            allowed-headers: "*"

eureka:
  client:
    service-url:
      defaultZone: http://my-eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true