server:
  port: 8080

spring:
  application:
    name: core
  datasource:
    username: 'myportfolio'
    url: jdbc:mysql://localhost:33061/core
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE