server:
  port: 8080

core-module-basic-path: "api/core"
scheduled-cron-expression:
  cache-eviction: "0 0 0 * * ?" # Every day at midnight
  #cache-eviction: "0 * * ? * *" # Every minute (Only for tests)

spring:
  application:
    name: core
  datasource:
    username: 'myportfolio'
    url: jdbc:mysql://mysql:3306/core
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ##### START CACHE CONFIGURATIONS #####
        cache:
          use_query_cache: true
          use_second_level_cache: true
          factory_class: org.redisson.hibernate.RedissonRegionFactory
          redisson:
            fallback: true
            config: redisson-dev-docker.yaml
        #####  END CACHE CONFIGURATIONS  #####
    hibernate:
      ddl-auto: none
  zipkin:
    base-url: http://myzipkin:9411
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://my-eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE